# Generated by Django 3.2.5 on 2021-08-08 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='faculty_name',
        ),
    ]
