# Generated by Django 3.2.5 on 2021-08-22 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_remove_classroom_faculty_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('assignDate', models.DateTimeField(auto_now_add=True)),
                ('dueDate', models.DateField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='classroom',
            name='readingMaterial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classroom.readingmaterial'),
        ),
    ]
