# Generated by Django 3.2.5 on 2021-08-22 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_auto_20210822_0855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='readingMaterial',
        ),
        migrations.AddField(
            model_name='readingmaterial',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classroom.classroom'),
        ),
    ]
