# Generated by Django 3.2.5 on 2021-08-22 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_auto_20210822_0936'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadingMaterial',
        ),
    ]
