# Generated by Django 3.2.5 on 2021-08-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_remove_classroom_faculty_name'),
        ('Account', '0003_alter_student_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='classroom',
            field=models.ManyToManyField(blank=True, null=True, to='classroom.ClassRoom'),
        ),
        migrations.AddField(
            model_name='student',
            name='classroom',
            field=models.ManyToManyField(blank=True, null=True, to='classroom.ClassRoom'),
        ),
    ]
